#=============================
# 时钟
#=============================
set_property PACKAGE_PIN     E20        [get_ports clk]
set_property IOSTANDARD     LVCMOS33    [get_ports clk]
create_clock -period 15.0    [get_ports clk]

#=============================
# 复位
#=============================
set_property PACKAGE_PIN     R18        [get_ports rst_n]
set_property IOSTANDARD     LVCMOS33    [get_ports rst_n]

#=============================
# 输出信号
#=============================
set_property PACKAGE_PIN U20 [get_ports {pc_o[31]}]
set_property PACKAGE_PIN AA2 [get_ports {pc_o[30]}]
set_property PACKAGE_PIN W20 [get_ports {pc_o[29]}]
set_property PACKAGE_PIN Y20 [get_ports {pc_o[28]}]
set_property PACKAGE_PIN W19 [get_ports {pc_o[27]}]
set_property PACKAGE_PIN V19 [get_ports {pc_o[26]}]
set_property PACKAGE_PIN U19 [get_ports {pc_o[25]}]
set_property PACKAGE_PIN T19 [get_ports {pc_o[24]}]
set_property PACKAGE_PIN T20 [get_ports {pc_o[23]}]
set_property PACKAGE_PIN U21 [get_ports {pc_o[22]}]
set_property PACKAGE_PIN V21 [get_ports {pc_o[21]}]
set_property PACKAGE_PIN W21 [get_ports {pc_o[20]}]
set_property PACKAGE_PIN Y21 [get_ports {pc_o[19]}]
set_property PACKAGE_PIN AA3 [get_ports {pc_o[18]}]
set_property PACKAGE_PIN V22 [get_ports {pc_o[17]}]
set_property PACKAGE_PIN U22 [get_ports {pc_o[16]}]
set_property PACKAGE_PIN T22 [get_ports {pc_o[15]}]
set_property PACKAGE_PIN T23 [get_ports {pc_o[14]}]
set_property PACKAGE_PIN AA4 [get_ports {pc_o[13]}]
set_property PACKAGE_PIN V23 [get_ports {pc_o[12]}]
set_property PACKAGE_PIN W23 [get_ports {pc_o[11]}]
set_property PACKAGE_PIN Y23 [get_ports {pc_o[10]}]
set_property PACKAGE_PIN W24 [get_ports {pc_o[9]}]
set_property PACKAGE_PIN V24 [get_ports {pc_o[8]}]
set_property PACKAGE_PIN U24 [get_ports {pc_o[7]}]
set_property PACKAGE_PIN T24 [get_ports {pc_o[6]}]
set_property PACKAGE_PIN AA5 [get_ports {pc_o[5]}]
set_property PACKAGE_PIN R23 [get_ports {pc_o[4]}]
set_property PACKAGE_PIN AA7 [get_ports {pc_o[3]}]
set_property PACKAGE_PIN AA8 [get_ports {pc_o[2]}]
set_property PACKAGE_PIN P23 [get_ports {pc_o[1]}]
set_property PACKAGE_PIN P24 [get_ports {pc_o[0]}]

set_property PACKAGE_PIN N21 [get_ports {inst_o[31]}]
set_property PACKAGE_PIN N22 [get_ports {inst_o[30]}]
set_property PACKAGE_PIN N23 [get_ports {inst_o[29]}]
set_property PACKAGE_PIN N24 [get_ports {inst_o[28]}]
set_property PACKAGE_PIN M21 [get_ports {inst_o[27]}]
set_property PACKAGE_PIN M22 [get_ports {inst_o[26]}]
set_property PACKAGE_PIN A18 [get_ports {inst_o[25]}]
set_property PACKAGE_PIN M24 [get_ports {inst_o[24]}]
set_property PACKAGE_PIN A19 [get_ports {inst_o[23]}]
set_property PACKAGE_PIN L22 [get_ports {inst_o[22]}]
set_property PACKAGE_PIN L23 [get_ports {inst_o[21]}]
set_property PACKAGE_PIN L24 [get_ports {inst_o[20]}]
set_property PACKAGE_PIN K21 [get_ports {inst_o[19]}]
set_property PACKAGE_PIN K22 [get_ports {inst_o[18]}]
set_property PACKAGE_PIN K23 [get_ports {inst_o[17]}]
set_property PACKAGE_PIN A20 [get_ports {inst_o[16]}]
set_property PACKAGE_PIN J21 [get_ports {inst_o[15]}]
set_property PACKAGE_PIN A25 [get_ports {inst_o[14]}]
set_property PACKAGE_PIN J23 [get_ports {inst_o[13]}]
set_property PACKAGE_PIN J24 [get_ports {inst_o[12]}]
set_property PACKAGE_PIN H21 [get_ports {inst_o[11]}]
set_property PACKAGE_PIN H22 [get_ports {inst_o[10]}]
set_property PACKAGE_PIN H23 [get_ports {inst_o[9]}]
set_property PACKAGE_PIN H24 [get_ports {inst_o[8]}]
set_property PACKAGE_PIN G21 [get_ports {inst_o[7]}]
set_property PACKAGE_PIN G22 [get_ports {inst_o[6]}]
set_property PACKAGE_PIN R22 [get_ports {inst_o[5]}]
set_property PACKAGE_PIN G24 [get_ports {inst_o[4]}]
set_property PACKAGE_PIN R25 [get_ports {inst_o[3]}]
set_property PACKAGE_PIN F22 [get_ports {inst_o[2]}]
set_property PACKAGE_PIN F23 [get_ports {inst_o[1]}]
set_property PACKAGE_PIN F24 [get_ports {inst_o[0]}]

set_property PACKAGE_PIN E21  [get_ports {reg_wdata_o[31]}]
set_property PACKAGE_PIN E22  [get_ports {reg_wdata_o[30]}]
set_property PACKAGE_PIN E23  [get_ports {reg_wdata_o[29]}]
set_property PACKAGE_PIN AA15 [get_ports {reg_wdata_o[28]}]
set_property PACKAGE_PIN D21  [get_ports {reg_wdata_o[27]}]
set_property PACKAGE_PIN AA17 [get_ports {reg_wdata_o[26]}]
set_property PACKAGE_PIN D23  [get_ports {reg_wdata_o[25]}]
set_property PACKAGE_PIN D24  [get_ports {reg_wdata_o[24]}]
set_property PACKAGE_PIN C21  [get_ports {reg_wdata_o[23]}]
set_property PACKAGE_PIN C22  [get_ports {reg_wdata_o[22]}]
set_property PACKAGE_PIN C23  [get_ports {reg_wdata_o[21]}]
set_property PACKAGE_PIN C24  [get_ports {reg_wdata_o[20]}]
set_property PACKAGE_PIN B21  [get_ports {reg_wdata_o[19]}]
set_property PACKAGE_PIN B22  [get_ports {reg_wdata_o[18]}]
set_property PACKAGE_PIN AA18 [get_ports {reg_wdata_o[17]}]
set_property PACKAGE_PIN B24  [get_ports {reg_wdata_o[16]}]
set_property PACKAGE_PIN AA19 [get_ports {reg_wdata_o[15]}]
set_property PACKAGE_PIN A22  [get_ports {reg_wdata_o[14]}]
set_property PACKAGE_PIN A23  [get_ports {reg_wdata_o[13]}]
set_property PACKAGE_PIN A24  [get_ports {reg_wdata_o[12]}]
set_property PACKAGE_PIN AA20 [get_ports {reg_wdata_o[11]}]
set_property PACKAGE_PIN AA22 [get_ports {reg_wdata_o[10]}]
set_property PACKAGE_PIN AA23 [get_ports {reg_wdata_o[9]}]
set_property PACKAGE_PIN AA24 [get_ports {reg_wdata_o[8]}]
set_property PACKAGE_PIN AA25 [get_ports {reg_wdata_o[7]}]
set_property PACKAGE_PIN AB1  [get_ports {reg_wdata_o[6]}]
set_property PACKAGE_PIN AB2  [get_ports {reg_wdata_o[5]}]
set_property PACKAGE_PIN AB4  [get_ports {reg_wdata_o[4]}]
set_property PACKAGE_PIN AB5  [get_ports {reg_wdata_o[3]}]
set_property PACKAGE_PIN AB6  [get_ports {reg_wdata_o[2]}]
set_property PACKAGE_PIN AB16 [get_ports {reg_wdata_o[1]}]
set_property PACKAGE_PIN AB17 [get_ports {reg_wdata_o[0]}]

set_property PACKAGE_PIN B17 [get_ports {reg_waddr_o[4]}]
set_property PACKAGE_PIN B19 [get_ports {reg_waddr_o[3]}]
set_property PACKAGE_PIN B20 [get_ports {reg_waddr_o[2]}]
set_property PACKAGE_PIN B25 [get_ports {reg_waddr_o[1]}]
set_property PACKAGE_PIN A17 [get_ports {reg_waddr_o[0]}]

set_property PACKAGE_PIN AC4 [get_ports reg_we_o]

#=============================
# 统一电平
#=============================
set_property IOSTANDARD LVCMOS33 [get_ports *]